"""Razorpay test-mode card payment helper.

Provides test card details and authorization guidance for the buyer agent.

**Why no server-side auto-pay?**
Razorpay authorizes card payments via a client-side token generated by
the checkout.js SDK.  There is no server-side API to simulate this.
The agent therefore returns the test card details and a short checkout
URL so the user (or a frontend automation step) can enter them.

Test cards (from https://razorpay.com/docs/payments/payments/test-card-upi-details/):
- Visa:      4111 1111 1111 1111
- Master:    5104 0100 0000 0008
- Amex:      3782 822463 10005
"""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Test card registry
# ---------------------------------------------------------------------------

TEST_CARDS: dict[str, dict[str, str]] = {
    "visa": {
        "number": "4111111111111111",
        "display": "4111 1111 1111 1111",
        "network": "Visa",
        "cvv": "123",
        "expiry": "12/29",
    },
    "mastercard": {
        "number": "5104010000000008",
        "display": "5104 0100 0000 0008",
        "network": "Mastercard",
        "cvv": "123",
        "expiry": "12/29",
    },
    "amex": {
        "number": "378282246310005",
        "display": "3782 822463 10005",
        "network": "American Express",
        "cvv": "1234",
        "expiry": "12/29",
    },
}

# Alias so callers can use "test_visa" or "visa"
_CARDS = {**TEST_CARDS, **{f"test_{k}": v for k, v in TEST_CARDS.items()}}


def get_test_card(card: str = "visa") -> dict[str, str]:
    """Return test card details for the given card name.

    Parameters
    ----------
    card : str
        One of ``visa``, ``mastercard``, ``amex`` (or ``test_visa``, etc.).

    Returns
    -------
    dict
        ``{ number, display, network, cvv, expiry }`` or ``{ error }``.
    """
    card_data = _CARDS.get(card.lower())
    if card_data is None:
        valid = ", ".join(sorted(set(TEST_CARDS.keys())))
        return {"error": f"Unknown test card '{card}'. Valid options: {valid}"}
    return card_data


def prepare_test_payment(
    *,
    order_id: str,
    amount_paise: int,
    currency: str = "INR",
    card: str = "visa",
) -> dict:
    """Build a complete test-payment context the agent can relay to the user.

    Returns everything needed to authorize a test payment:
    - The order and amount
    - Test card details
    - Step-by-step instructions

    Parameters
    ----------
    order_id : str
        Razorpay order ID.
    amount_paise : int
        Amount in paise.
    currency : str
        Currency code.
    card : str
        Test card to use (default ``visa``).

    Returns
    -------
    dict
        ``{ order_id, amount_paise, currency, card, instructions }``
    """
    card_data = get_test_card(card)
    if "error" in card_data:
        return card_data

    logger.info(
        "Test payment prepared for order=%s amount=%d card=%s",
        order_id,
        amount_paise,
        card_data["network"],
    )

    return {
        "order_id": order_id,
        "amount_paise": amount_paise,
        "amount_inr": f"{amount_paise / 100:.2f}",
        "currency": currency,
        "card": card_data,
        "instructions": (
            f"To complete the test payment:\n"
            f"1. Open the Razorpay checkout for order {order_id}\n"
            f"2. Enter card number: {card_data['display']}\n"
            f"3. Expiry: {card_data['expiry']}, CVV: {card_data['cvv']}\n"
            f"4. Submit to authorize the payment\n"
            f"5. Call complete_checkout with session_id to verify"
        ),
    }
